
CREATE DATABASE Veterinaria

CREATE TABLE [dbo].[Usuarios](
	[id_usuario] [int] IDENTITY(1,1),
	[usuario] [varchar](50),
	[password] [varchar](10),
	[email] [varchar](50) ,	
	[borrado] [bit],
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						 
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED ([id_usuario])
)


CREATE TABLE [dbo].[Tipos](
	[id_tipo] [int] IDENTITY(1,1),
	[t_descrip] [varchar](50),	
	[borrado] [bit],
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						 
 CONSTRAINT [PK_Tipos] PRIMARY KEY CLUSTERED 	([id_tipo]) 
)

CREATE TABLE [dbo].[Clientes](
	[id_cliente] [int] IDENTITY(1,1),
	[c_nombre] [varchar](50),	
	[sexo] [bit],
	[borrado] [bit],
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						 
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 	([id_cliente]) 
)



CREATE TABLE [dbo].[Mascotas](
	[id_mascota] [int] IDENTITY(1,1),
	[m_nombre] [varchar](50),	
	[edad] [int],
	[id_tipo] [int],
	[id_cliente] [int],
	[borrado] [bit],
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						 
 CONSTRAINT [PK_Mascotas] PRIMARY KEY CLUSTERED 	([id_mascota]) ,
 CONSTRAINT [FK_Mascotas_Tipo] FOREIGN KEY  ([id_tipo])
	REFERENCES [dbo].[Tipos]  ([id_tipo]) ,
CONSTRAINT [FK_Mascotas_Cliente] FOREIGN KEY  ([id_cliente])
	REFERENCES [dbo].[Clientes]  ([id_cliente]) 

)


CREATE TABLE [dbo].[Atencion](
	[id_atencion] [int] IDENTITY(1,1),
	[fecha] [datetime],
	[a_descrip] [varchar](50),	
	[importe] [decimal](18, 0),
	[id_mascota] [int],
	[id_usuario] [int],
	[borrado] [bit],
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																						 
 CONSTRAINT [PK_Atencion] PRIMARY KEY CLUSTERED 	([id_atencion]) ,
 CONSTRAINT [FK_Atencion_Mascota] FOREIGN KEY  ([id_mascota])
	REFERENCES [dbo].[Mascotas]  ([id_mascota]),
CONSTRAINT [FK_Atencion_Usuario] FOREIGN KEY  ([id_usuario])
	REFERENCES [dbo].[Usuarios]  ([id_usuario])
)


insert into Usuarios (usuario,password, borrado) values ('a',1,0)
insert into Usuarios (usuario,password, borrado) values ('b',1,0)
insert into Usuarios (usuario,password, borrado) values ('c',1,1)




